use std::fs;
use std::process::Command;

#[test]
fn test_cli_stdout_output() {
    let temp_dir = std::env::temp_dir().join("aidl_rs_test_stdout");
    let _ = fs::create_dir_all(&temp_dir);
    let input_path = temp_dir.join("ITestService.aidl");

    let aidl_content = r#"
package com.example;

interface ITestService {
    int getFoo();
    void setFoo(int val);
}
"#;

    fs::write(&input_path, aidl_content).expect("Failed to write test aidl file");

    let bin_path = env!("CARGO_BIN_EXE_aidl-rs");
    let output = Command::new(bin_path)
        .arg(&input_path)
        .output()
        .expect("Failed to execute aidl-rs CLI binary");

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("// Auto-generated by aidl-rs"));
    assert!(stdout.contains("pub trait ITestService"));
    assert!(stdout.contains("fn getFoo(&self) -> Result<i32, String>;"));
    assert!(stdout.contains("fn setFoo(&self, val: i32) -> Result<(), String>;"));

    let _ = fs::remove_dir_all(&temp_dir);
}

#[test]
fn test_cli_file_output() {
    let temp_dir = std::env::temp_dir().join("aidl_rs_test_file_output");
    let _ = fs::create_dir_all(&temp_dir);
    let input_path = temp_dir.join("IFoo.aidl");
    let output_path = temp_dir.join("foo_bindings.rs");

    let aidl_content = r#"
package com.example;

parcelable FooData {
    int id;
    String name;
}
"#;

    fs::write(&input_path, aidl_content).expect("Failed to write test aidl file");

    let bin_path = env!("CARGO_BIN_EXE_aidl-rs");
    let output = Command::new(bin_path)
        .arg(&input_path)
        .arg("-o")
        .arg(&output_path)
        .output()
        .expect("Failed to execute aidl-rs CLI binary");

    assert!(output.status.success());
    assert!(output_path.exists());

    let content = fs::read_to_string(&output_path).expect("Failed to read output file");
    assert!(content.contains("// Auto-generated by aidl-rs"));
    assert!(content.contains("pub struct FooData"));
    assert!(content.contains("pub id: i32,"));
    assert!(content.contains("pub name: String,"));

    let _ = fs::remove_dir_all(&temp_dir);
}

#[test]
fn test_cli_file_not_found() {
    let bin_path = env!("CARGO_BIN_EXE_aidl-rs");
    let output = Command::new(bin_path)
        .arg("non_existent_file_12345.aidl")
        .output()
        .expect("Failed to execute aidl-rs CLI binary");

    assert!(!output.status.success());
}
