use crate::ast::*;

fn last_rust_ident(name: &str) -> &str {
    name.rsplit('.').next().unwrap_or(name)
}

pub struct Generator {
    pub generate_binder_stubs: bool,
}

impl Default for Generator {
    fn default() -> Self {
        Self {
            generate_binder_stubs: true,
        }
    }
}

impl Generator {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn generate_file(&self, file: &AidlFile) -> String {
        let mut out = String::new();

        out.push_str("// Auto-generated by aidl-rs from AIDL definition.\n");
        out.push_str("// DO NOT EDIT DIRECTLY.\n\n");
        out.push_str("#[allow(non_snake_case)]\n");
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("#[allow(unused_variables)]\n\n");

        if let Some(ref pkg) = file.package {
            out.push_str(&format!("// Package: {}\n\n", pkg));
        }

        for decl in &file.decls {
            match decl {
                AidlDecl::Interface(iface) => {
                    out.push_str(&self.generate_interface(iface));
                }
                AidlDecl::Parcelable(parcelable) => {
                    out.push_str(&self.generate_parcelable(parcelable));
                }
                AidlDecl::Enum(enm) => {
                    out.push_str(&self.generate_enum(enm));
                }
                AidlDecl::Union(un) => {
                    out.push_str(&self.generate_union(un));
                }
            }
            out.push_str("\n");
        }

        out
    }

    pub fn generate_interface(&self, iface: &AidlInterface) -> String {
        let mut out = String::new();

        let trait_super = iface
            .extends
            .as_deref()
            .map(last_rust_ident)
            .map(|name| format!("{name} + "))
            .unwrap_or_default();
        out.push_str(&format!("pub trait {}: {}Send + Sync {{\n", iface.name, trait_super));

        // Constants inside interface
        for c in &iface.constants {
            let rty = aidl_type_to_rust(&c.ty);
            out.push_str(&format!("    pub const {}: {} = {};\n", c.name, rty, c.value));
        }
        if !iface.constants.is_empty() {
            out.push_str("\n");
        }

        // Methods
        for method in &iface.methods {
            let ret_ty = aidl_type_to_rust(&method.return_type);
            let ret_str = if ret_ty == "()" {
                "Result<(), String>".to_string()
            } else {
                format!("Result<{}, String>", ret_ty)
            };

            let args_str = method
                .args
                .iter()
                .map(|arg| {
                    let rty = aidl_type_to_rust(&arg.ty);
                    format!("{}: {}", arg.name, rty)
                })
                .collect::<Vec<_>>()
                .join(", ");

            if args_str.is_empty() {
                out.push_str(&format!("    fn {}(&self) -> {};\n", method.name, ret_str));
            } else {
                out.push_str(&format!(
                    "    fn {}(&self, {}) -> {};\n",
                    method.name, args_str, ret_str
                ));
            }
        }

        out.push_str("}\n\n");

        // Transaction code module
        out.push_str(&format!("pub mod {}_transactions {{\n", iface.name));
        let mut auto_id = 0u32;
        for method in &iface.methods {
            let tx_id = method.id.unwrap_or_else(|| {
                let curr = auto_id;
                auto_id += 1;
                curr
            });
            out.push_str(&format!(
                "    pub const TRANSACTION_{}: u32 = FIRST_CALL_TRANSACTION + {};\n",
                method.name, tx_id
            ));
        }
        out.push_str("    pub const FIRST_CALL_TRANSACTION: u32 = 1;\n");
        out.push_str("}\n\n");

        if self.generate_binder_stubs {
            // Generate proxy struct stub
            out.push_str(&format!("pub struct {}Proxy<B> {{\n", iface.name));
            out.push_str("    pub binder: B,\n");
            out.push_str("}\n\n");

            out.push_str(&format!("impl<B> {}Proxy<B> {{\n", iface.name));
            out.push_str("    pub fn new(binder: B) -> Self {\n");
            out.push_str("        Self { binder }\n");
            out.push_str("    }\n");
            out.push_str("}\n");
        }

        out
    }

    pub fn generate_parcelable(&self, parcelable: &AidlParcelable) -> String {
        let mut out = String::new();

        if parcelable.fields.is_empty() {
            out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Default)]\n");
            out.push_str(&format!("pub struct {};\n", parcelable.name));
            return out;
        }

        out.push_str("#[derive(Debug, Clone, PartialEq, Default)]\n");
        out.push_str(&format!("pub struct {} {{\n", parcelable.name));
        for field in &parcelable.fields {
            let rty = aidl_type_to_rust(&field.ty);
            out.push_str(&format!("    pub {}: {},\n", field.name, rty));
        }
        out.push_str("}\n\n");

        out.push_str(&format!("impl {} {{\n", parcelable.name));
        out.push_str("    pub fn new(");
        let params = parcelable
            .fields
            .iter()
            .map(|f| format!("{}: {}", f.name, aidl_type_to_rust(&f.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&params);
        out.push_str(") -> Self {\n");
        out.push_str("        Self {\n");
        for field in &parcelable.fields {
            out.push_str(&format!("            {},\n", field.name));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");

        out
    }

    pub fn generate_enum(&self, enm: &AidlEnum) -> String {
        let mut out = String::new();

        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
        out.push_str("#[repr(i32)]\n");
        out.push_str(&format!("pub enum {} {{\n", enm.name));

        for (idx, variant) in enm.variants.iter().enumerate() {
            if let Some(ref val) = variant.value {
                out.push_str(&format!("    {} = {},\n", variant.name, val));
            } else {
                out.push_str(&format!("    {} = {},\n", variant.name, idx));
            }
        }

        out.push_str("}\n");
        out
    }

    pub fn generate_union(&self, un: &AidlUnion) -> String {
        let mut out = String::new();

        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str(&format!("pub enum {} {{\n", un.name));

        for field in &un.fields {
            let rty = aidl_type_to_rust(&field.ty);
            let variant_name = capitalize_first(&field.name);
            out.push_str(&format!("    {}({}),\n", variant_name, rty));
        }

        out.push_str("}\n");
        out
    }
}

pub fn aidl_type_to_rust(ty: &AidlType) -> String {
    let base = match ty.name.as_str() {
        "void" => "()".to_string(),
        "boolean" => "bool".to_string(),
        "byte" => "i8".to_string(),
        "char" => "u16".to_string(),
        "int" => "i32".to_string(),
        "long" => "i64".to_string(),
        "float" => "f32".to_string(),
        "double" => "f64".to_string(),
        "String" | "Utf8String" => "String".to_string(),
        "IBinder" => "String".to_string(),
        "ParcelFileDescriptor" => "std::fs::File".to_string(),
        "List" => {
            if let Some(inner) = ty.generic_args.first() {
                format!("Vec<{}>", aidl_type_to_rust(inner))
            } else {
                "Vec<String>".to_string()
            }
        }
        "Map" => {
            let k = ty
                .generic_args
                .get(0)
                .map(aidl_type_to_rust)
                .unwrap_or_else(|| "String".to_string());
            let v = ty
                .generic_args
                .get(1)
                .map(aidl_type_to_rust)
                .unwrap_or_else(|| "String".to_string());
            format!("std::collections::HashMap<{}, {}>", k, v)
        }
        other => {
            if ty.generic_args.is_empty() {
                other.to_string()
            } else {
                let g = ty
                    .generic_args
                    .iter()
                    .map(aidl_type_to_rust)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}<{}>", other, g)
            }
        }
    };

    let mut res = base;
    for _ in 0..ty.array_dimensions {
        res = format!("Vec<{}>", res);
    }

    if ty.is_nullable {
        res = format!("Option<{}>", res);
    }

    res
}

fn capitalize_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
